env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-alert: error
  no-console: error
  no-var: error
  no-undef: off